# Generated by Django 3.2.16 on 2022-10-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linebotapp', '0002_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='notify',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
